name: Validating code

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compile
        run: make

      - name: Run
        run: make run

      - name: Installing valgrind
        run: sudo apt install -y valgrind

      - name: Installing ncurses
        run: sudo apt install -y libncurses5-dev libncursesw5-dev

      - name: Memory Checking
        run: make valgrind
