name: Validating code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: make run
      run: make run
      
    - name: make valgrind
      run: make valgrind
