name: Validating code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Compile
      run: make
      
    - name: Run
      run: make run
      
    - name: Installing valgrind
      run: sudo apt install -y valgrind
      
    - name: Memory Checking
      run: make valgrind
